### ISSUE TITLE
Use WSL's systemd new systemd support

### ISSUE THREAD

**Issue by tudurom** [nix-community/NixOS-WSL#133]
## Problem
Announced two days ago, WSL now has native support for starting a distro using systemd. Details here: https://devblogs.microsoft.com/commandline/systemd-support-is-now-available-in-wsl/

Maybe this would simplify the current solution with the `syschemd` script, or maybe remove it altogether?

**Comment by nzbr** [comment]
@K900 has already started work on that. Unfortunately, it's not going to be as simple as on other distros, because we need to run the system's activation script before starting systemd. The goal is to have both as an option in order to keep backwards compatibility to Windows 10 and older WSL versions

**Comment by K900** [comment]
My prototype is here: https://gitlab.com/K900/yoink

It should work if built statically and put into /lib/systemd/systemd (yes, exactly that path).

**Comment by nzbr** [comment]
Native Systemd support (#134) has been merged! You can try it by setting `wsl.nativeSystemd = true`
