### ISSUE TITLE
How do I remove NixOS-WSL

### ISSUE THREAD

**Issue by BruceEckel** [nix-community/NixOS-WSL#194]
I followed the instructions and it got to
`starting systemd`
and it just hung and never got any further.

Now if I try to start it it says:
```
> wsl -d NixOS
Failed to attach disk 'C:\Users\Bruce\Downloads\NixOS\ext4.vhdx' to WSL2: The system cannot find the file specified.
Error code: Wsl/Service/CreateInstance/MountVhd/ERROR_FILE_NOT_FOUND
```

If I try to re-install it it says:
```
> wsl --import NixOS .\NixOS\ nixos-wsl-installer.tar.gz --version 2
Import in progress, this may take a few minutes.
A distribution with the supplied name already exists.
Error code: Wsl/Service/0x800700b7
```

But NixOS does not show up in the list of programs that I can remove (as Ubuntu does).

How can I clean this up? Thanks.

**Comment by BruceEckel** [comment]
And now I just found this which seems to solve the problem:
https://github.com/nix-community/NixOS-WSL/issues/156
(Until it is fixed it would be nice to include these steps in the standard installation instructions so everyone doesn't have to go through this ... or give up before they figure it out).

**Comment by philallen117** [comment]
When I ran into the `systemd `issue with `nixos-wsl-installer.tar.gz`, I unregistered and then used the alternative archive `nixos-wsl-x86_64-linux.tar.gz` as suggested by @nzbr in the [release notes](https://github.com/nix-community/NixOS-WSL/releases/tag/22.05-5c211b47).
I am a little nervous about this, since there must be *some* reason for listing the archives in the stated order?

**Comment by nzbr** [comment]
In theory, `nixos-wsl-installer.tar.gz` is the correct one. It is a wrapper around the other tarball, as that can't be imported (fails with an "Unspecified error") if the system that it's built on uses hard links in the nix store (i.e. if `nix-store --optimize` was used). There's a bug in the installer tarball attached to the release that somehow breaks systemd (the bug has since been fixed). The `nixos-wsl-x86_64-linux.tar.gz` attached to the release does not contain any hard links and can therefore be imported as well. Which tarball is used should not make any difference once the distro has been installed

**Comment by K900** [comment]
Do we have anything else that needs to be done here?

**Comment by SuperSandro2000** [comment]
I don't think so.
