### ISSUE TITLE
Hostname is not set on boot

### ISSUE THREAD

**Issue by uzytkownik** [nix-community/NixOS-WSL#276]
## Bug description
When hostname is set in `configuration.nix`, it is not set on boot. `hostname` returns the Windows hostname.

## To Reproduce

1. Set hostname
2. Rebuild nix
3. See hostname is updated
4. Reboot guest
5. See that hostname is not updated
6. Run `nixos-rebuild switch`
7. See hostname is updated

**Expected behavior**
Hostname is set on boot

**Comment by nzbr** [comment]
I can't reproduce it right now. When I change the hostname it persists across WSL reboots. Do you have `nixos-wsl-version` on your system, and if yes, what does it report?

**Comment by uzytkownik** [comment]
@nzbr I don't. I'm using 22.11 from installer and haven't change the wsl flakes.

**Comment by nzbr** [comment]
It seems like it's actually not working on the version included with the latest installer.
Can you try updating to the latest commit on the main branch? Assuming you're importing the module the way it came in the installer, do the following:

Make sure to create a backup of the disto's content if there's anything important in there, then run
```bash
cd /etc/nixos
sudo rm -rf nixos-wsl
sudo nix-shell -p wget --run "wget https://github.com/nix-community/NixOS-WSL/archive/refs/heads/main.zip"
sudo nix-shell -p unzip --command "unzip main.zip"
sudo mv NixOS-WSL-main/ nixos-wsl
sudo nix-channel --add https://nixos.org/channels/nixos-23.05 nixos
sudo nix-channel --update
sudo nixos-rebuild switch
```

(Otherwise adapt these steps to whatever you have changed)
Let me know if you need assistance or have any further questions (and yes, we're working on making the update process less cumbersome)

**Comment by K900** [comment]
Should be fine in 23.05 and latest WSL.
