### ISSUE TITLE
Documentation for people who manage multiple different systems using flakes

### ISSUE THREAD

**Issue by leonbreedt** [nix-community/NixOS-WSL#278]
## Problem

I am using an existing flake setup to manage my NixOS configuration for macOS (using nix-darwin), and NixOS proper.

## Solution

Is there any documentation/suggestion on cleanly bootstrapping the WSL distribution, and from then on, managing it using my own flake? I would like to manage all three environments using the same flake, rather than rely on someone else's flake.

If it is possible to compose the two, even better!

**Comment by nzbr** [comment]
You can add this repo as a flake input and add `<thisInput>.nixosModules.wsl` to your imports. After that, create a configuration that has the options from `configuration.nix` set. You can then create a tarball with `nix build <flake>#nixosConfigurations.<configName>.config.system.build.installer`. The system can then be updated like any other NixOS install

Make sure that you don't have `wsl.nativeSystemd` enabled while building the installer, because the installer does not have native systemd support yet

**Comment by leonbreedt** [comment]
@nzbr: Thanks for the super helpful response. Worked without a hitch!

**Comment by nzbr** [comment]
Nice! Glad I could help
