### ISSUE TITLE
issue with getting nixos-wsl working with nixos-vscode-server:

### ISSUE THREAD

**Issue by zeta-00** [nix-community/NixOS-WSL#31]
Hello @Trundle ,

Just thought that maybe you could take a look at this nixos-vscode-server issue that I'm having, it might have something to do with nixos-wsl because I'm unable to get them connected and working?

https://github.com/msteen/nixos-vscode-server/issues/2

Thanks in advance for the help!

**Comment by Reilithion** [comment]
I have had trouble using vscode with nixos-wsl too. Wasn't aware there was a nixos-vscode-server. I am also interested in a solution to this problem.

**Comment by tudurom** [comment]
As @Reilithion commented [here](https://github.com/Trundle/NixOS-WSL/issues/29#issuecomment-834720002), you can try setting a password for your account and running `sudo login`. This will start systemd's user session and start your daemon.

**Comment by nzbr** [comment]
The underlying issue is, that the systemd user deamon does not get started, because no session for the user is ever started.  
The user-mode deamon can be started by running `systemctl start user@nixos.service` (assuming that nixos is the username of the default user). This will work temporarily until WSL is restarted for the next time.  
My permanent fix was to add the following to my configuration.nix:  
```nix
  systemd.services.autostart-user-daemon = {
    wants = [ "user@${defaultUser}.service" ];
    wantedBy = [ "multi-user.target" ];
    path = [ pkgs.coreutils ];
    script = "true";
  };
```

This adds a unit that does nothing itself, but depends on the `user@`-unit and is started automatically, causing the `user@`-unit to be started when WSL starts.

**Comment by tudurom** [comment]
As of 89c644e7178abc4abf51e4d1c82222ec18f9878a the systemd user daemon gets started and many issues get fixed too. Make sure to update!

**Comment by nzbr** [comment]
The user daemon does indeed get started now and nixos-vscode-server works. However, trying to connect with the WSL remote in VSCode fails now (log attached). I managed to connect by enabling the SSH server in NixOS and then using the SSH remote to connect to localhost, but that is more of a workaround than a real fix

[Log file](https://github.com/Trundle/NixOS-WSL/files/6554932/wsllog.txt)

**Comment by zeta-00** [comment]
I'm also able to get nixos-vscode-server to load nixos in windows vscode, but whenever I try to load the terminal or nix-env-selector I get errors similar to @nzbr . I'm going to use ubuntu+nix in wsl for now, until this issue gets fixed,
thanks in advance for helping fix this issue!

**Comment by nzbr** [comment]
The terminal does not work, because the nixos-vscode-server package uses an outdated version of nodejs. There are two open PRs against the nixos-vscode-server repo that fix this issue. The issue with the terminal is not limited to NixOS-WSL but instead affects NixOS installations on real hardware as well. As a workaround I am using my fork of the nixos-vscode-server repo until one of the PRs gets merged

**Comment by zeta-00** [comment]
@nzbr ,

Thanks, I'll take a look at that,
and here's a similar issue if any of you want to take a look:

https://github.com/msteen/nixos-vscode-server/issues/2

**Comment by izzues** [comment]
> As of [89c644e](https://github.com/Trundle/NixOS-WSL/commit/89c644e7178abc4abf51e4d1c82222ec18f9878a) the systemd user daemon gets started and many issues get fixed too. Make sure to update!

Hey, sorry for the stupid question, but how would I go about updating? Do I have to build the tarball from source and do `wsl --import [...]` again?

Thanks for your great work!

**Comment by tudurom** [comment]
Extremely late reply but...

You mostly update only the nix and sh files, you manually merge the changes in your own config.

**Comment by nzbr** [comment]
A fix has been merged and is included in the latest release
