### ISSUE TITLE
Native docker support

### ISSUE THREAD

**Issue by nzbr** [nix-community/NixOS-WSL#59]
Using Docker Desktop from within NixOS now works if it is enabled with `wsl.docker.enable = true;`.  
It would be great, to additionally have the option to use the native Linux-version of docker directly from NixOS like on a bare-metal installation. In the past this was possible by just enabling docker. As of NixOS 21.11 however [a kernel that supports nftables is required](https://github.com/nix-community/NixOS-WSL/pull/56#issuecomment-1048758804)

**Comment by grantbevis** [comment]
I have experience with this and can take a look

**Comment by grantbevis** [comment]
Difficulty is @nzbr, users would have to compile their own WSL2 kernel and modify/create a .wslconfig file to point and use the kernel with nftables modules in. Happy to provide instructions but it's not for the faint of heart. From my understanding we can't change the kernel in the NixOS distro because WSL provides the kernel itself.

Happy to add a write up/README.md PR, what's your thoughts?

**Comment by nzbr** [comment]
I have activated the repos wiki. You should be able to put a page there now
Another option (although I don't know if it's feasible) would be to somehow override the change that causes docker to break in NixOS 21.11. It should be possible _somehow_, given that it worked in 20.09

**Comment by grantbevis** [comment]
The difference is systemd v249 has switched to nftables. You can add `--iptables=false` (I think, from memory!) to get the docker service to start inside NixOS WSL but you then have no container networking which isn't very fun!

**Comment by nzbr** [comment]
This fixes it for me:

```nix
  nixpkgs.overlays = [
      (self: super: {
        docker = super.docker.override { iptables = pkgs.iptables-legacy; };
      })
    ];
```
