### ISSUE TITLE
nsenter: failed to parse pid: '-p'

### ISSUE THREAD

**Issue by michas2** [nix-community/NixOS-WSL#69]
I just imported the current version of the installer:
```
wsl --import NixOS .\NixOS\ .\Downloads\nixos-wsl-installer.tar.gz --version 2
```

When I try to run it I get an error:
```
> wsl -d NixOS
nsenter: failed to parse pid: '-p'
```

**Comment by Hajitorus** [comment]
I got around this by touching the systemd.pid file.

**Comment by grantbevis** [comment]
I can reproduce this @nzbr using [nixos-wsl-installer.tar.gz](https://github.com/nix-community/NixOS-WSL/releases/download/21.11-d89f18a1/nixos-wsl-installer.tar.gz)

Using [nixos-wsl-installer-fixed.tar.gz](https://github.com/nix-community/NixOS-WSL/releases/download/21.11-d89f18a1/nixos-wsl-installer-fixed.tar.gz) Works, can you try the `fixed` release @michas2 please?

**Comment by michas2** [comment]
Now it starts fine. Thanks! :)

**Comment by michas2** [comment]
When running a second time I get this:
```
> wsl -d NixOS
/bin/sh: line 1: cd: /root: Permission denied
```
Any idea where this comes from?

**Comment by nzbr** [comment]
What is the host-path that you ran wsl in?
In my experience, this happens, when WSL does not know which directory to start the shell in. Because the default user is set to root, it defaults to /root. Syschdemd then drops to the default user, who has no read permission on /root - thus resulting in that error. sh notices this and changes to the current users home (/home/nixos if you didn't change the username)

**Comment by michas2** [comment]
I simply ran it as described above:
```
wsl --import NixOS .\NixOS\ .\Downloads\nixos-wsl-installer-fixed.tar.gz --version 2
wsl -d NixOS
```
I ran it in powershell in my (default) user directory.

(I also noticed that `/mnt/c/` is not mounted. not sure if that is on purpose or maybe a result of the failing command.)

**Comment by michas2** [comment]
BTW, after that error, the shell runs as user `nixos` in `/home/nixos` afterwards.

**Comment by nzbr** [comment]
There is no /bin/mount in the installer. That leads to `/mnt/*` not being mounted, which in turn means that WSL can't cd to the current working directory (so it defaults to /root). For now you should be able to fix this by running `wsl -t NixOS` to restart the distribution once.
Could you open a separate issue for this? So that it gets addressed in a future release

**Comment by michas2** [comment]
Will do. Thanks!
